name: Mock CI Pipeline

on:
  push:
    branches:
      - TestPipeline  # Target the new branch
  pull_request:
    branches:
      - TestPipeline  # Trigger on PRs to this branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"  # Kept the same as your original

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install torch torchvision  # Explicitly install required packages
          # If you have a requirements.txt, uncomment the next line and adjust
          pip install -r requirements.txt

      - name: Run Unit Tests with Unittest
        env:
          CI: "true"  # Enable mock mode for tests
        run: |
          python -m unittest discover -s . -p "test_*.py"  # Discover all test files

      #- name: Run Tests with Pytest
      #  run: pytest src/  # Uncomment if you switch to pytest later